//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdp.LangResx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rdp.LangResx.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            } set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 现在重启么? 的本地化字符串。
        /// </summary>
        internal static string msg_IS_RESTART{get {return ResourceManager.GetString("msg_IS_RESTART", resourceCulture);}}
        internal static string form1_tsItemLabel_together{get { return ResourceManager.GetString("form1_tsItemLabel_together", resourceCulture); }}
        internal static string form1_tsItemLabel_bar{get { return ResourceManager.GetString("form1_tsItemLabel_bar", resourceCulture); }}



        internal static string host_Load_1 { get { return ResourceManager.GetString("host_Load_1", resourceCulture); } }
        internal static string host_Load_2 { get { return ResourceManager.GetString("host_Load_2", resourceCulture); } }
        internal static string host_add_1 { get { return ResourceManager.GetString("host_add_1", resourceCulture); } }
        internal static string host_add_2 { get { return ResourceManager.GetString("host_add_2", resourceCulture); } }
        internal static string host_add_3 { get { return ResourceManager.GetString("host_add_3", resourceCulture); } }
        internal static string host_add_4 { get { return ResourceManager.GetString("host_add_4", resourceCulture); } }
        internal static string host_add_5 { get { return ResourceManager.GetString("host_add_5", resourceCulture); } }
        internal static string host_add_6 { get { return ResourceManager.GetString("host_add_6", resourceCulture); } }
        internal static string msg_IS_en_ch { get { return ResourceManager.GetString("msg_IS_en_ch", resourceCulture); } }
        internal static string msg_password_no { get { return ResourceManager.GetString("msg_password_no", resourceCulture); } }
        internal static string msg_title { get { return ResourceManager.GetString("msg_title", resourceCulture); } }
        internal static string msg_data_null { get { return ResourceManager.GetString("msg_data_null", resourceCulture); } }
        internal static string run_exe { get { return ResourceManager.GetString("run_exe", resourceCulture); } }
        internal static string run_rar { get { return ResourceManager.GetString("run_rar", resourceCulture); } }
        internal static string run_AxInterop { get { return ResourceManager.GetString("run_AxInterop", resourceCulture); } }
        internal static string run_Interop { get { return ResourceManager.GetString("run_Interop", resourceCulture); } }

        internal static string msg_del_fail { get { return ResourceManager.GetString("msg_del_fail", resourceCulture); } }
        internal static string msg_del_title { get { return ResourceManager.GetString("msg_del_title", resourceCulture); } }
        internal static string msg_del_yes_no { get { return ResourceManager.GetString("msg_del_yes_no", resourceCulture); } }
        internal static string msg_fail { get { return ResourceManager.GetString("msg_fail", resourceCulture); } }

        internal static string link { get { return ResourceManager.GetString("link", resourceCulture); } }
        internal static string link_desktop { get { return ResourceManager.GetString("link_desktop", resourceCulture); } }
        internal static string link_break { get { return ResourceManager.GetString("link_break", resourceCulture); } }
        internal static string fz_display { get { return ResourceManager.GetString("fz_display", resourceCulture); } }
        internal static string fz_no_display { get { return ResourceManager.GetString("fz_no_display", resourceCulture); } }
        internal static string bj { get { return ResourceManager.GetString("bj", resourceCulture); } }
        internal static string bj_display { get { return ResourceManager.GetString("bj_display", resourceCulture); } }
        internal static string bj_no_display { get { return ResourceManager.GetString("bj_no_display", resourceCulture); } }

        internal static string list_bz { get { return ResourceManager.GetString("list_bz", resourceCulture); } }
        internal static string list_name { get { return ResourceManager.GetString("list_name", resourceCulture); } }
        internal static string list_server { get { return ResourceManager.GetString("list_server", resourceCulture); } }
        internal static string list_user_name { get { return ResourceManager.GetString("list_user_name", resourceCulture); } }


        internal static string fz_count { get { return ResourceManager.GetString("fz_count", resourceCulture); } }
        internal static string fz_name { get { return ResourceManager.GetString("fz_name", resourceCulture); } }
        internal static string ini_Audio_0 { get { return ResourceManager.GetString("ini_Audio_0", resourceCulture); } }
        internal static string ini_Audio_1 { get { return ResourceManager.GetString("ini_Audio_1", resourceCulture); } }
        internal static string ini_Audio_2 { get { return ResourceManager.GetString("ini_Audio_2", resourceCulture); } }
        internal static string ini_Color_0 { get { return ResourceManager.GetString("ini_Color_0", resourceCulture); } }
        internal static string ini_Color_1 { get { return ResourceManager.GetString("ini_Color_1", resourceCulture); } }
        internal static string ini_Color_2 { get { return ResourceManager.GetString("ini_Color_2", resourceCulture); } }
        internal static string ini_Color_3 { get { return ResourceManager.GetString("ini_Color_3", resourceCulture); } }
        internal static string ini_Color_4 { get { return ResourceManager.GetString("ini_Color_4", resourceCulture); } }

        internal static string ini_Network_0 { get { return ResourceManager.GetString("ini_Network_0", resourceCulture); } }
        internal static string ini_Network_1 { get { return ResourceManager.GetString("ini_Network_1", resourceCulture); } }
        internal static string ini_Network_2 { get { return ResourceManager.GetString("ini_Network_2", resourceCulture); } }
        internal static string ini_Network_3 { get { return ResourceManager.GetString("ini_Network_3", resourceCulture); } }
        internal static string ini_Network_4 { get { return ResourceManager.GetString("ini_Network_4", resourceCulture); } }
        internal static string ini_Network_5 { get { return ResourceManager.GetString("ini_Network_5", resourceCulture); } }
        internal static string ini_Width_Height { get { return ResourceManager.GetString("ini_Width_Height", resourceCulture); } }
        internal static string list_name_name { get { return ResourceManager.GetString("list_name_name", resourceCulture); } }
        internal static string list_name_name_px { get { return ResourceManager.GetString("list_name_name_px", resourceCulture); } }
        internal static string ping_err { get { return ResourceManager.GetString("ping_err", resourceCulture); } }
        internal static string ping_out { get { return ResourceManager.GetString("ping_out", resourceCulture); } }
        internal static string link_host_err { get { return ResourceManager.GetString("link_host_err", resourceCulture); } }
        internal static string link_host_null { get { return ResourceManager.GetString("link_host_null", resourceCulture); } }
        internal static string link_host_max { get { return ResourceManager.GetString("link_host_max", resourceCulture); } }

        






    }
}
